# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UImainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 895)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonBZ = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonBZ.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonBZ.setObjectName("pushButtonBZ")
        self.verticalLayout.addWidget(self.pushButtonBZ)
        self.pushButtonRemoveOuterArea = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonRemoveOuterArea.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonRemoveOuterArea.setObjectName("pushButtonRemoveOuterArea")
        self.verticalLayout.addWidget(self.pushButtonRemoveOuterArea)
        self.pushButtonRemoveNoise = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonRemoveNoise.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonRemoveNoise.setObjectName("pushButtonRemoveNoise")
        self.verticalLayout.addWidget(self.pushButtonRemoveNoise)
        self.pushButtonRemoveSmallArea = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonRemoveSmallArea.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonRemoveSmallArea.setObjectName("pushButtonRemoveSmallArea")
        self.verticalLayout.addWidget(self.pushButtonRemoveSmallArea)
        self.pushButtonWshed = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonWshed.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonWshed.setObjectName("pushButtonWshed")
        self.verticalLayout.addWidget(self.pushButtonWshed)
        self.pushButtonCanny = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonCanny.setEnabled(False)
        self.pushButtonCanny.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonCanny.setCheckable(False)
        self.pushButtonCanny.setChecked(False)
        self.pushButtonCanny.setObjectName("pushButtonCanny")
        self.verticalLayout.addWidget(self.pushButtonCanny)
        self.pushButtonGetEdgeAndNumber = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonGetEdgeAndNumber.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonGetEdgeAndNumber.setObjectName("pushButtonGetEdgeAndNumber")
        self.verticalLayout.addWidget(self.pushButtonGetEdgeAndNumber)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonCalcContact = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonCalcContact.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonCalcContact.setObjectName("pushButtonCalcContact")
        self.horizontalLayout_2.addWidget(self.pushButtonCalcContact)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButtonOutputSomeParm = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonOutputSomeParm.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonOutputSomeParm.setObjectName("pushButtonOutputSomeParm")
        self.verticalLayout.addWidget(self.pushButtonOutputSomeParm)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonBackOne = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonBackOne.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonBackOne.setObjectName("pushButtonBackOne")
        self.verticalLayout.addWidget(self.pushButtonBackOne)
        self.pushButtonSave = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.verticalLayout.addWidget(self.pushButtonSave)
        self.pushButtonLoadImage = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonLoadImage.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonLoadImage.setObjectName("pushButtonLoadImage")
        self.verticalLayout.addWidget(self.pushButtonLoadImage)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.imageDis = QtWidgets.QLabel(self.groupBox)
        self.imageDis.setMinimumSize(QtCore.QSize(800, 800))
        self.imageDis.setText("")
        self.imageDis.setObjectName("imageDis")
        self.gridLayout.addWidget(self.imageDis, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout.setStretch(1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1022, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButtonBZ.clicked.connect(MainWindow.pushButtonBinaryzation)
        self.pushButtonLoadImage.clicked.connect(MainWindow.pushButtonLoadimage)
        self.pushButtonBackOne.clicked.connect(MainWindow.pushButtonBOne)
        self.pushButtonRemoveOuterArea.clicked.connect(MainWindow.pushButtonROuterArea)
        self.pushButtonRemoveNoise.clicked.connect(MainWindow.pushButtonRNoise)
        self.pushButtonCanny.clicked.connect(MainWindow.pushButtonCannys)
        self.pushButtonRemoveSmallArea.clicked.connect(MainWindow.pushButtonRSmallArea)
        self.pushButtonWshed.clicked.connect(MainWindow.pushButtonWatershed)
        self.pushButtonSave.clicked.connect(MainWindow.pushButtonSaveImage)
        self.pushButtonGetEdgeAndNumber.clicked.connect(MainWindow.pushButtonGetEdgeAndNum)
        self.pushButtonCalcContact.clicked.connect(MainWindow.pushButtonCalcContacts)
        self.pushButtonOutputSomeParm.clicked.connect(MainWindow.pushButtonOutputParm)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "操作按钮"))
        self.pushButtonBZ.setText(_translate("MainWindow", "二值化"))
        self.pushButtonRemoveOuterArea.setText(_translate("MainWindow", "移除最外层纹理"))
        self.pushButtonRemoveNoise.setText(_translate("MainWindow", "移除噪声"))
        self.pushButtonRemoveSmallArea.setText(_translate("MainWindow", "移除小碎块"))
        self.pushButtonWshed.setText(_translate("MainWindow", "分水岭"))
        self.pushButtonCanny.setText(_translate("MainWindow", "canny(暂时遗弃)"))
        self.pushButtonGetEdgeAndNumber.setText(_translate("MainWindow", "去除外层框"))
        self.pushButtonCalcContact.setText(_translate("MainWindow", "计算接触"))
        self.pushButtonOutputSomeParm.setText(_translate("MainWindow", "输出图片和参数"))
        self.pushButtonBackOne.setText(_translate("MainWindow", "返回上一步"))
        self.pushButtonSave.setText(_translate("MainWindow", "存储当前图片"))
        self.pushButtonLoadImage.setText(_translate("MainWindow", "导入图片"))
        self.groupBox.setTitle(_translate("MainWindow", "预处理图片"))

